### ISSUE TITLE
https://github.com/pountzas/Capstone-Webapp-API/projects/2

### ISSUE THREAD

**Issue by pountzas** [pountzas/Capstone-Webapp-API#21]
Unfortunately I am alone my partner will not go on.

**Comment by mricanho** [comment]
# Status: ✔️ Project Approved ✔️ 

Hello @pountzas🔥
 
It's a shame that your partner let you in this instance, but it's an unexpected challenge that you can conquer, so good job so far! Your Kanban's up and running!👍🏽 

![shine team](https://user-images.githubusercontent.com/60631456/128784868-da7be6b2-b46b-4627-af21-b178bb9a7bf7.gif)

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by pountzas** [comment]
Thanks a lot.
